Add kron(): kronecker product for 2D matrices
rust-ndarray/ndarray pull request #1039
Opened 2021-06-20 20:21 UTC by notmgsk

Closes https://github.com/rust-ndarray/ndarray/issues/652

H/T @ethanhs

2021-06-20 20:36 UTC, ethanhs approved these changes
LGTM

2021-06-21 17:50 UTC, bluss approved these changes
Looks straightforward

2021-06-21 17:50 UTC, bluss requested changes
Oh, request changes would be the rather better summary. :slightly_smiling_face:

2021-06-21 20:16 UTC, ethanhs commented on src/linalg/impl_linalg.rs
> +pub fn kron<T>(a: &Array2<T>, b: &Array2<T>) -> Array2<T>
I think `kron` would align with numpy, as a datapoint, just wanted to mention. It also is an operation usually done on 2 dimensional matrices, though I believe numpy supports higher dimensional kronecker products.

2021-10-31 03:06 UTC, ethanhs commented
@notmgsk Are you interested in continuing to work on this? If not I will probably build off of this PR and respond to the review.

2021-11-06 01:11 UTC, ethanhs commented
I went ahead and made #1105, which I think responds to the feedback here.

2021-11-11 20:08 UTC, bluss commented
Superseded by  #1105

2021-11-11 20:08 UTC, closed without merging